// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQT7mLxkv3S7EJ5webXNZRRUicy6Gr2M',
    appId: '1:448844255047:web:8452e16fd1c0514dd58662',
    messagingSenderId: '448844255047',
    projectId: 'psw-journal-journey',
    authDomain: 'psw-journal-journey.firebaseapp.com',
    storageBucket: 'psw-journal-journey.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0O0tdlbvNlKTrEj3Cmc8F8Zp4t4f_CNU',
    appId: '1:448844255047:android:2b08f7316f4c0ab7d58662',
    messagingSenderId: '448844255047',
    projectId: 'psw-journal-journey',
    storageBucket: 'psw-journal-journey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUtrfd-TpxP_PUXH9yEBgJr2SLg0JKq8s',
    appId: '1:448844255047:ios:e73f664329b1c3a9d58662',
    messagingSenderId: '448844255047',
    projectId: 'psw-journal-journey',
    storageBucket: 'psw-journal-journey.appspot.com',
    iosBundleId: 'com.example.pswJournalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUtrfd-TpxP_PUXH9yEBgJr2SLg0JKq8s',
    appId: '1:448844255047:ios:e73f664329b1c3a9d58662',
    messagingSenderId: '448844255047',
    projectId: 'psw-journal-journey',
    storageBucket: 'psw-journal-journey.appspot.com',
    iosBundleId: 'com.example.pswJournalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtQT7mLxkv3S7EJ5webXNZRRUicy6Gr2M',
    appId: '1:448844255047:web:2d68978e28fd7ff3d58662',
    messagingSenderId: '448844255047',
    projectId: 'psw-journal-journey',
    authDomain: 'psw-journal-journey.firebaseapp.com',
    storageBucket: 'psw-journal-journey.appspot.com',
  );
}
